# Generated by Django 4.2.15 on 2024-08-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_constructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AlterField(
            model_name='constructor',
            name='constructor_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
