# Generated by Django 4.2.13 on 2024-08-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_constructor_id_remove_driver_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('grid_id', models.IntegerField()),
                ('field_one', models.CharField(max_length=100)),
                ('field_two', models.CharField(max_length=100)),
                ('guess_count', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('driver_id',)},
            },
        ),
    ]
