# Generated by Django 4.2.13 on 2024-08-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_driverguess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverguess',
            unique_together={('driver_id', 'grid_id', 'field_one', 'field_two')},
        ),
    ]
